### ISSUE TITLE
완료 버튼 컴포넌트화 적용 요청 및 대표 색상 설정

### ISSUE THREAD

**Issue by bluebluerabbit** [2022-2-CTS/React-Front-End#3]
### 완료 버튼 컴포넌트화
CompleteButton 이라는 컴포넌트로 만들어놨으니까 사용 부탁드립니다.
회원가입, 닉네임설정 화면에는 적용시켜놓았음
정보공유 글 작성 화면에 적용 필요함 
@leejyohan 

### 대표 색상 적용
대표 색상 : #1F83EB
-> 지금까지 'bg-[#1F83EB]' 이렇게 해놓은 것들 'bg-main'로 변경 부탁함. 테일윈드 config에 추가해놓았음
@jiho9702 @leejyohan

**Comment by leejyohan** [comment]
확인 수정했습니다

**Comment by bluebluerabbit** [comment]
확인
