### ISSUE TITLE
UI 디테일 수정

### ISSUE THREAD

**Issue by bluebluerabbit** [2022-2-CTS/React-Front-End#4]
@leejyohan 

**postWrite.js**
- input 상하좌우 margin 추가 (글이 너무 딱붙어서 써져요)
- 내용 input은 textarea로 할 것, 텍스트가 상단부터 써지게, 상하좌우 margin 추가

**post.js**
- 마지막 글은 하단 bar 없애주세요! (글 나누는 bar)

**Comment by leejyohan** [comment]
수정했습니다
